---
abstract: 'Interface to the L<gosmore(1)> and L<OSRM|http://routed.sourceforge.net/> routing libraries'
author:
  - 'Ævar Arnfjörð Bjarmason <avar@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geo-Routing
no_index:
  directory:
    - t
requires:
  Any::Moose: 0
  Class::Load: 0
  Cwd: 0
  Data::Dumper: 0
  File::Basename: 0
  Geo::Distance::XS: 0
  HTML::Entities: 0
  IPC::System::Simple: 0
  Text::Trim: 0
  WWW::Mechanize: 0
  XML::SAX::Expat: 0
  XML::Simple: 0
  autodie: 0
  namespace::clean: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Geo-Routing
  homepage: http://search.cpan.org/dist/Geo-Routing/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/avar/geo-routing.git
version: 0.08
x_authority: cpan:AVAR
